config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  get '/admin', to: 'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show]
    patch '/orders/:id', to: 'orders#update', as: "orders_update"
    patch '/order_details/:id', to: 'order_details#update', as: "orderdetails"
  end
  #顧客用
  devise_for :customers, skip: [:passwords,], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  root to: 'customer/homes#top'
  namespace :customer do
    get '/my_page', to: 'customers#show'
    get '/edit', to: 'customers#edit', as: "customer_edit"
    patch '/customers', to: 'customers#update'
    get '/unsubscribed', to: 'customers#unsubscribed'
    patch '/withdraw', to: 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/destroy_all', to: 'cart_items#destroy_all'
    resources :addresses, only: [:index, :create, :edit, :update]
    delete '/address/:id', to: 'addresses#destroy'
    resources :orders, only: [:new, :index]
    post '/orders/confirm', to: 'orders#confirm'
    post '/orders', to: 'orders#create', as: 'order_create'
    get '/orders/complete', to: 'orders#complete'
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_kana, presence: true
  validates :last_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :tel_number, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :order_details, through: :orders

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + first_name + ' ' + last_name
  end
end

app/models/order.rb
class Order < ApplicationRecord

  enum method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 配送準備中: 3, 配送済み: 4 }
  belongs_to :customer
  has_many :order_details

  def shipping_address_display
    '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end

 def order_statuses
   Order.order_statuses
 end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @orderdetail = OrderDetail.find(params[:id])
    @order.postage = 500
    @order_items = @order.order_details
    @total = @order_items.inject(0) { |sum, order_item| sum +  order_item.subtotal_order }
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.order_status == "入金確認"
      @order_details.each do |order_detail|
        order_detail.production_status = "製作待ち"
        order_detail.save
      end
    end
    redirect_to  admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :item_amount, :postage, :order_status, :method, :shipping_postal_code, :shipping_address, :shipping_name)
  end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  def index
    @address = Address.new
    @addresses = Address.all
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to customer_addresses_path
    else
      @addresses = Address.all
      render :index
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to customer_addresses_path
    else
      render :edit
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to customer_addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :correct_customer, only: [:index, :create, :destroy, :destroy_all]

  def index
    @cart_items = CartItem.all
    @total = @cart_items.inject(0) { |sum, cart_item| sum +  cart_item.subtotal }
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    cart_item = CartItem.find_by(customer_id: current_customer.id, item_id: cart_item_params[:item_id])
    if cart_item
      new_quantity = cart_item.amount + @cart_item.amount
      cart_item.update_attribute(:amount, new_quantity)
      @cart_item.delete
      redirect_to customer_cart_items_path
    else
      @cart_item.customer_id = current_customer.id
      @cart_item.save
      redirect_to customer_cart_items_path
    end
  end

  def update
    @cartitem = CartItem.find(params[:id])
    @cartitem.update(amount: params[:amount].to_i)
    redirect_to customer_cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to customer_cart_items_path
  end

  def destroy_all
    @cart_item = CartItem.all
    @cart_item.destroy_all
    redirect_to customer_cart_items_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

  def correct_customer
    unless customer_signed_in?
      redirect_to customer_items_path, alert: "ログインしてください"
    end
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_my_page_path
    else
      render :edit
    end

  end

  def unsubscribed
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_unsubscribed: true)
    reset_session
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_kana, :last_kana, :postal_code, :address, :tel_number, :email)
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
    @params = params[:id]
    if @params
      @genre = Genre.find(params[:id])
    end
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :correct_customer, only: [:new]

  def new
    @order = Order.new
  end

  def confirm
    @cart_items = CartItem.all
    @total = @cart_items.inject(0) { |sum, cart_item| sum +  cart_item.subtotal }
    @order = Order.new
    if  params[:order][:address_option] == "0"
      @order = Order.new(order_params)
      @order.shipping_postal_code = current_customer.postal_code
      @order.shipping_address = current_customer.address
      @order.shipping_name = current_customer.first_name + current_customer.last_name
    elsif params[:order][:address_option] == "1"
      @order = Order.new(order_params)
      @address = Address.find(params[:order][:address_id])
      @order.shipping_postal_code = @address.postal_code
      @order.shipping_address = @address.address
      @order.shipping_name = @address.name
    elsif params[:order][:address_option] == "2"
      @order = Order.new(order_params)
      @order.save
    else
      flash[:alert] = "お届け先を選んでください"
      render :new
    end
    @order.postage = 800
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item.id
        order_detail.order_id = @order.id
        order_detail.quantity = cart_item.amount
        order_detail.purchase_price = cart_item.item.price
        order_detail.save
      end
      redirect_to customer_orders_complete_path
      cart_items.destroy_all
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :method, :shipping_postal_code, :shipping_address, :shipping_name, :item_amount)
  end

  def correct_customer
    @cart_items = CartItem.all
    unless @cart_items.exists?
      redirect_to customer_cart_items_path, alert: 'カートに商品を追加してください'
    end
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def after_sign_in_path_for(resource)
    customer_my_page_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  # POST /resource
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_kana, :last_kana, :postal_code, :address, :tel_number, :emails])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  def after_sign_in_path_for(resource)
    customer_my_page_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if @customer.valid_password?(params[:customer][:password]) && !(@customer.is_unsubscribed == false)
      redirect_to root_path
    end
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/complete.html.erb
<div class="text-center">
  <h1>ご注文ありがとうございました!</h1>
</div>

app/views/customer/orders/confirm.html.erb
<h2>注文情報確認</h2>

<div class="contaner">
<div class="row justify-content-center">
  <table class="table table-bordered" style="width: 65%">
    <thead>
      <tr class="table-secondary">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= image_tag cart_item.item.get_item_image(100,100) %><%= cart_item.item.name %></td>
        <td><%= cart_item.item.with_tax_price %></td>
        <td><%= cart_item.amount %></td>
        <td><%= cart_item.subtotal %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <table class="table" style="width: 20%">
    <tbody>
      <tr>
        <td class="table-secondary">送料</td>
        <td><%= @order.postage %></td>
      </tr>
      <tr>
        <td class="table-secondary">合計金額</td>
        <td><%= @total.round.to_s(:delimited)%></td>
      </tr>
      <tr>
        <td class="table-secondary">請求金額</td>
        <td><%= (@order.postage+@total).round.to_s(:delimited) %></td>
      </tr>
    </tbody>
  </table>
</div>

  <div class="row">
    <div class="col-md-8">支払方法<%= @order.method_i18n %></div>
  </div>
  <div class="row">
    <div class="col-md-8">お届け先<%= @order.shipping_address_display %></div>
  </div>
</div>
<%= form_with model: @order, url: customer_order_create_path, method: :post do |f| %>
<%= f.hidden_field :shipping_postal_code, :value => @order.shipping_postal_code %>
<%= f.hidden_field :shipping_address, :value => @order.shipping_address %>
<%= f.hidden_field :shipping_name, :value => @order.shipping_name %>
<%= f.hidden_field :method, :value => @order.method %>
<%= f.hidden_field :item_amount, :value => @order.postage+@total %>
<div class="text-center"><%= f.submit "注文を確定する", class: "btn btn-success", data: {confirm: "注文を確定しますか？"} %></div>
<% end %>

app/views/customer/orders/index.html.erb
<h1>Customer::Orders#index</h1>
<p>Find me in app/views/customer/orders/index.html.erb</p>

app/views/customer/orders/new.html.erb
<div class="contaner">

<h2 class="text-center">注文情報入力</h2>

<%= form_with model: @order, url: customer_orders_confirm_path do |f| %>
<div class="d-flex flex-column" style="height: 100px;">
  <label class="col-form-label">支払方法</label>
    <div class="flex">
      <%= f.radio_button :method, Order.methods.key(0) %>
      <%= f.label :method, Order.methods.key(0) %>
    </div>
    <div class="flex">
      <%= f.radio_button :method, Order.methods.key(1) %>
      <%= f.label :method, Order.methods.key(1)%>
    </div>
</div>
<h4><%= alert %></h4>
<div class="d-flex flex-column" style="height: 400px;">
  <label class="col-form-label">お届け先</label>
    <div class="flex">
      <%= f.radio_button :address_option,0 %>
      ご自身の住所<br>
      <%= f.label :address_id, current_customer.address_display%>
    </div>
    <div class="flex">
      <%= f.radio_button :address_option,1 %>
      登録済み住所から選択<br>
      <%= f.select :address_id, options_from_collection_for_select(Address.all, :id, :address_display) %>
    </div>
    <div class="flex">
      <%= f.radio_button :address_option,2 %>
      新しい配送先
    <div class="flex">
      <%= f.label :shipping_postal_code, "郵便番号" %>
      <%= f.text_field :shipping_postal_code, autofocus: true, autocomplete: "shipping_postal_code" %>
    </div>
    <div class="flex">
      <%= f.label :shipping_address, "住所" %>
      　　<%= f.text_field :shipping_address, autofocus: true, autocomplete: "shipping_address" %>
    </div>
    <div class="flex">
      <%= f.label :shipping_name, "宛名" %>
      　　<%= f.text_field :shipping_name, autofocus: true, autofocus: "shipping_name" %>
    </div>
</div>
<div class="center-block">
  <%= f.submit "確認画面に進む", class: 'btn btn-primary' %>
  <% end %>
</div>
</div>

app/views/customer/orders/show.html.erb
<h1>Customer::Orders#show</h1>
<p>Find me in app/views/customer/orders/show.html.erb</p>