config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  get '/admin', to: 'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show]
    patch '/orders/:id', to: 'orders#update', as: "orders_update"
    patch '/order_details/:id', to: 'order_details#update', as: "orderdetails"
  end
  #顧客用
  devise_for :customers, skip: [:passwords,], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  root to: 'customer/homes#top'
  namespace :customer do
    get '/my_page', to: 'customers#show'
    get '/edit', to: 'customers#edit', as: "customer_edit"
    patch '/customers', to: 'customers#update'
    get '/unsubscribed', to: 'customers#unsubscribed'
    patch '/withdraw', to: 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete '/destroy_all', to: 'cart_items#destroy_all'
    resources :addresses, only: [:index, :create, :edit, :update]
    delete '/address/:id', to: 'addresses#destroy'
    resources :orders, only: [:new, :index]
    post '/orders/confirm', to: 'orders#confirm'
    post '/orders', to: 'orders#create', as: 'order_create'
    get '/orders/complete', to: 'orders#complete'
  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  enum method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 配送準備中: 3, 配送済み: 4 }
  belongs_to :customer
  has_many :order_details

  def shipping_address_display
    '〒' + shipping_postal_code + ' ' + shipping_address + ' ' + shipping_name
  end

 def order_statuses
   Order.order_statuses
 end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @orderdetail = OrderDetail.find(params[:id])
    @order.postage = 500
    @order_items = @order.order_details
    @total = @order_items.inject(0) { |sum, order_item| sum +  order_item.subtotal_order }
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.order_status == "入金確認"
      @order_details.each do |order_detail|
        order_detail.production_status = "製作待ち"
        order_detail.save
      end
    end
    redirect_to  admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :item_amount, :postage, :order_status, :method, :shipping_postal_code, :shipping_address, :shipping_name)
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :correct_customer, only: [:new]

  def new
    @order = Order.new
  end

  def confirm
    @cart_items = CartItem.all
    @total = @cart_items.inject(0) { |sum, cart_item| sum +  cart_item.subtotal }
    @order = Order.new
    if  params[:order][:address_option] == "0"
      @order = Order.new(order_params)
      @order.shipping_postal_code = current_customer.postal_code
      @order.shipping_address = current_customer.address
      @order.shipping_name = current_customer.first_name + current_customer.last_name
    elsif params[:order][:address_option] == "1"
      @order = Order.new(order_params)
      @address = Address.find(params[:order][:address_id])
      @order.shipping_postal_code = @address.postal_code
      @order.shipping_address = @address.address
      @order.shipping_name = @address.name
    elsif params[:order][:address_option] == "2"
      @order = Order.new(order_params)
      @order.save
    else
      flash[:alert] = "お届け先を選んでください"
      render :new
    end
    @order.postage = 800
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item.id
        order_detail.order_id = @order.id
        order_detail.quantity = cart_item.amount
        order_detail.purchase_price = cart_item.item.price
        order_detail.save
      end
      redirect_to customer_orders_complete_path
      cart_items.destroy_all
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :method, :shipping_postal_code, :shipping_address, :shipping_name, :item_amount)
  end

  def correct_customer
    @cart_items = CartItem.all
    unless @cart_items.exists?
      redirect_to customer_cart_items_path, alert: 'カートに商品を追加してください'
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h2>注文一覧</h2>
<div class="container">
  <div class="row justify-content-center">
    <table class="table table-borderd border border-dark" style="width: 60%">
      <thead>
        <tr class="table-secondary">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td>
          <%= link_to admin_order_path(order) do %>
            <%= l order.created_at %>
          <% end %>
        </td>
        <td><%= order.customer.first_name %> <%= order.customer.last_name %></td>
        <td><%= order.order_details.sum(:quantity) %></td>
        <td>
            <%= order.order_status_i18n %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="contaner">

  <h2>注文履歴詳細</h2>
  <div class="row mb-3">
    <div class="col-sm-2">購入者</div>
    <div class="col-sm-10"><%= @order.customer.first_name %><%= @order.customer.last_name %></div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-2">注文日</div>
    <div class="col-sm-10"><%= @order.created_at %></div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-2">配送先</div>
    <div class="col-sm-10"><%= @order.shipping_address_display %></div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-2">支払方法</div>
    <div class="col-sm-10"><%= @order.method_i18n %></div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-2">注文ステータス</div>
    <div class="col-sm-10">
      <%= form_with model: @order, url: admin_orders_update_path, method: :patch do |f| %>
        <%= f.select :order_status, *[Order.order_statuses.keys], { selected: @order.order_status_i18n } %>
        <%= f.submit "更新", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

  <div class="row">
  <table class="table table-bordered" style="width: 70%">
    <thead>
      <tr class="table-secondary">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.item.name %></td>
        <td><%= order_item.item.with_tax_price %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.subtotal_order %></td>
        <td>
          <%= form_with model: @orderdetail, url: admin_orderdetails_path(order_item), method: :patch do |f| %>
            <%= f.select :production_status, *[OrderDetail.production_statuses.keys], { selected: order_item.production_status_i18n } %>
            <%= f.submit "更新", class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <table style="width: 20%">
    <tbody>
      <tr>
        <td>送料</td>
        <td><%= @order.postage %></td>
      </tr>
      <tr>
        <td>合計金額</td>
        <td><%= @total.round.to_s(:delimited)%></td>
      </tr>
      <tr>
        <td>請求金額</td>
        <td><%= (@order.postage+@total).round.to_s(:delimited) %></td>
      </tr>
    </tbody>
  </table>
  </div>
</div>